### PR TITLE
Updating LICENSE to v3.0

### PR DESCRIPTION
**Pull request by lilyclements**
@dannyparsons after our discussion, I have updated this LICENSE to v3.0.

If you are happy with this, can it be merged?

### CODE REVIEW

**Comment by dannyparsons** [comment]
Looks good to me. We just need approval from the repo contributors to change the license.

@volloholic @Margherita-IDEMS @cabrinenyona Could you confirm you are happy with this change? We are updating the license from v2.1 to the newer v3.

**Comment by volloholic** [comment]
I agree the others should comment here too for reference

**Comment by dannyparsons** [comment]
@Margherita-IDEMS @cabrinenyona could you please comment here to confirm you are having with this change?

**Comment by cabrinenyona** [comment]
It looks good to me.

**Comment by Margherita-IDEMS** [comment]
Yes, that's fine! Hope you're all well.

**Pull request merged**
